### ISSUE TITLE
Privafox ESR?

### ISSUE THREAD

**Issue by dimqua** [intika/privafox-firefox#6]
How do you feel about creation a Privafox edition based on the current Firefox ESR version? In this case, you can even use Tor Browser as a base of your set.

**Comment by intika** [comment]
Okay it's not asking a lot i will add windows/linux esr... am not pro tor, but i will have a look at that ;)

**Comment by intika** [comment]
ESR is coming in v2, and for tor i will not bundle TBB because it's need a lot of work/maintenance to make it efficient, it's better to just use TBB when needing Tor, now... applying Privafox to Tor is not recommended because some settings may be not suitable for TBB

**Comment by intika** [comment]
Finally dropped this never ending release and you have an ESR and **TBB** :D version :) this is beta for TBB right now we will see how things go
